language: node_js
deploy:
  api_key:
    secure: igOdCGMob/kxpGIklRbwuYqkrtXwqdCtUN2zQ05bCBWzKBk1NQHm9zQo/2HHcKltVh8Y3/WnZz/30+Jr+u5jcSnFZrm77DvQQZk3pu1aj/hQai6MEAEuh82ab7B5RbsJBWPgSq1zvCCitoWxd7TBQXMHHhwzWZGku72SLBtlo36E7LLH3f/lBYlcXzR8b1GiEs0HhOmSMZwtkYHiZBK1G8+sJslpYPC5dY3T1ARNK/l8BJG26VRcyDdIA4c0/Y1B0p+DpzVKKv0CyLE6//07Tim+jdAavmHJxKlMNBRs5HQBof2judYCeEP3WHTPG1tJCQhXQsaKFrhhfCrA/CqGKxQ0m0vL2io0KNei/i47k7nYXQw84zKGyBLNSBOhsiLLWLxy7Qn0A9memBzRJhcLx71MRy9cpTHit89q5Fx5+tASMDAMHQ4uDsHyXo6izjhvzzRAwt6YXowbZ1RhKMuVWvACubMjylJyNNsYh31bHWPHCpDTqJawlYFiDijZC7mfVrwDyCJOyhUxa/ngHIGcs1aBcVhsRN0mc5I4S+fCZSJEgZLjx1Ei26I+Ra6dcpISxDr3X561xRMU3F+GhaSy4E470UIT+3Ver7htkdK57j3PcuxAZ17sKvKqj3WXoYnBqeqAMVNLxuHR+1rcCvOEgRmog8tMdH2silsNB3dTvrI=
  email: contact@rezo-zero.com
  provider: npm
